linters-settings:
  golint:
    # set the confidence level of a problem before it is reported. Setting it to 0 will show every issue from golint.
    min-confidence: 0
  gocyclo:
    # a minimal complexity of function to report it
    min-complexity: 70
  gocognit:
    # minimal code complexity to report
    min-complexity: 70
  goconst:
    # only report strings with the minimum given length
    min-len: 2
    # report from how many occurrence
    min-occurrences: 2
  funlen:
    # We have very long type definitions for K8s resources
    lines: 250
    statements: 100

run:
  # Skip lint on tests files
  tests: false
  timeout: 10m

linters:
  enable-all: true
  disable:
    - dupl
    - maligned
    - unparam
    - lll
    - gochecknoinits
    - gochecknoglobals
    - wsl
    - godox
    - gocritic
    - wrapcheck
    - varnamelen
    - nestif
    - nosprintfhostport
    - nilnil
    - goerr113
    - ireturn
    - gci
    - ifshort
    - forcetypeassert
    - exhaustivestruct
    - exhaustruct
    - exhaustive
    - errorlint
    - cyclop
    - maintidx
    - gofumpt
    - scopelint
    - interfacer
    - golint
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - wastedassign
