os:
  - linux

language: go
go: 1.13.x

env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - CHANGE_MINIKUBE_NONE_USER=true
    - KUBECONFIG=$HOME/.kube/config

stages:
  - name: lint
  - name: compile
  - name: docker
  # - name: test
  - name: publish master
    if: branch = master and type NOT IN (pull_request)
  - name: publish tag
    if: tag IS present

jobs:
  include:
    - script: make code/check code/lint
      stage: lint
    - script: make code/compile
      stage: compile
    - script:
        - make setup/operator-sdk
        - make code/docker version=latest
      stage: docker
    # NO TEST FOR THE MOMENT
    # - script:
    #     - go get github.com/mattn/goveralls
    #     - go get github.com/modocache/gover
    #     - make test/unit test/e2e test/goveralls
    #   stage: test
    - script:
        - make setup/operator-sdk
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make release/docker version=latest
        - make release/docker version=master
      stage: publish master
    - script:
        - make setup/operator-sdk
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make release/docker version=${TRAVIS_TAG}
      stage: publish tag
