sudo: required

language: go
go: 1.13.x

env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - CHANGE_MINIKUBE_NONE_USER=true
    - KUBECONFIG=$HOME/.kube/config

stages:
  - name: lint
  - name: compile
  - name: docker
  # - name: test
  - name: publishMaster
    if: branch = travis
  - name: publishTag
    if: tag IS present

job:
  include:
    - script: make code/check code/lint
      stage: lint
    - script: make code/compile
      stage: compile
    - script:
        - make setup/operator-sdk
        - make code/docker version=latest
      stage: docker
    # NO TEST FOR THE MOMENT
    # - script:
    #     - go get github.com/mattn/goveralls
    #     - go get github.com/modocache/gover
    #     - make test/unit test/e2e test/goveralls
    #   stage: test
    - script:
        - make setup/operator-sdk
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - make release/docker version=latest
        - make release/docker version=master
      stage: publishMaster
    - script:
        - make setup/operator-sdk
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - make release/docker version=${TRAVIS_TAG}
      stage: publishTag
