apiVersion: postgresql.easymile.com/v1alpha1
kind: PostgresqlBackup
metadata:
  name: pg-dump-gzip-to-s3
spec:
  # Link to the PostgresqlDatabase to back up.
  # Refers to config/samples/database/simple.yaml
  database:
    name: simple
    # namespace: default

  # Link to the PostgresqlBackupProvider that defines the CronJob template.
  # Refers to config/samples/backupprovider/pg-dump-gzip-to-s3.yaml
  backupProvider:
    name: pg-dump-gzip-to-s3
    # namespace: default

  # Override the provider schedule for this specific backup.
  # Leave unset to use the schedule defined in the BackupProvider.
  # schedule: "0 3 * * *"
