# permissions for end users to view postgresqluserroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresqluserrole-viewer-role
rules:
- apiGroups:
  - postgresql.easymile.com
  resources:
  - postgresqluserroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgresql.easymile.com
  resources:
  - postgresqluserroles/status
  verbs:
  - get
