# permissions for end users to edit postgresqluserroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresqluserrole-editor-role
rules:
- apiGroups:
  - postgresql.easymile.com
  resources:
  - postgresqluserroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgresql.easymile.com
  resources:
  - postgresqluserroles/status
  verbs:
  - get
