# permissions for end users to edit postgresqlengineconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresqlengineconfiguration-editor-role
rules:
- apiGroups:
  - postgresql.easymile.com
  resources:
  - postgresqlengineconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgresql.easymile.com
  resources:
  - postgresqlengineconfigurations/status
  verbs:
  - get
