# permissions for end users to view postgresqlengineconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresqlengineconfiguration-viewer-role
rules:
- apiGroups:
  - postgresql.easymile.com
  resources:
  - postgresqlengineconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgresql.easymile.com
  resources:
  - postgresqlengineconfigurations/status
  verbs:
  - get
