---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgresql.easymile.com
  resources:
  - postgresqlbackupproviders
  - postgresqlbackups
  - postgresqldatabases
  - postgresqlengineconfigurations
  - postgresqlpublications
  - postgresqluserroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgresql.easymile.com
  resources:
  - postgresqlbackupproviders/finalizers
  - postgresqlbackups/finalizers
  - postgresqldatabases/finalizers
  - postgresqlengineconfigurations/finalizers
  - postgresqlpublications/finalizers
  - postgresqluserroles/finalizers
  verbs:
  - update
- apiGroups:
  - postgresql.easymile.com
  resources:
  - postgresqlbackupproviders/status
  - postgresqlbackups/status
  - postgresqldatabases/status
  - postgresqlengineconfigurations/status
  - postgresqlpublications/status
  - postgresqluserroles/status
  verbs:
  - get
  - patch
  - update
