apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgresql-operator
  template:
    metadata:
      labels:
        name: postgresql-operator
    spec:
      serviceAccountName: postgresql-operator
      containers:
        - name: postgresql-operator
          # Replace this with the built image name
          image: easymile/postgresql-operator:1.0.1
          command:
            - postgresql-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "postgresql-operator"
