{{- if and .Values.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "postgresql-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "postgresql-operator.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "postgresql-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
