apiVersion: postgresql.easymile.com/v1alpha1
kind: PostgresqlUserRole
metadata:
  name: managed-simple
spec:
  # Mode
  mode: MANAGED
  # Role prefix to be used for user created in database engine
  rolePrefix: "managed-simple"
  # Privileges
  privileges:
    - # Privilege for the selected database
      privilege: OWNER
      # Connection type to be used for secret generation (Can be set to BOUNCER if wanted and supported by engine configuration)
      connectionType: PRIMARY
      # Database link
      database:
        name: simple
      # Generated secret name with information for the selected database
      generatedSecretName: managed-simple
  # Role attributes
  # Note: Only attributes that aren't conflicting with operator are supported.
  roleAttributes:
    # REPLICATION attribute
    # Note: This can be either true, false or null (to ignore this parameter)
    replication: null # false / true for example
    # BYPASSRLS attribute
    # Note: This can be either true, false or null (to ignore this parameter)
    bypassRLS: null # false / true for example
    # CONNECTION LIMIT connlimit attribute
    # Note: This can be either -1, a number or null (to ignore this parameter)
    # Note: Increase your number by one because operator is using the created user to perform some operations.
    connectionLimit: null # 10 for example
