apiVersion: postgresql.easymile.com/v1alpha1
kind: PostgresqlDatabase
metadata:
  name: schemas
spec:
  # Engine configuration link
  engineConfiguration:
    # Resource name
    name: simple
    # Resource namespace
    # Will use resource namespace if not set
    # namespace:
  # Database name
  database: databasename
  # Schemas
  schemas:
    # List of schemas to enable
    list:
      - schema1
    # Should drop on delete ?
    # Default set to false
    # If set to false, removing from list won't delete schema from database
    dropOnDelete: true
    # Delete schema with cascade
    # Default set to false
    # For all elements that have used the deleted schema
    deleteWithCascade: true


